Readme tutorial
paraynaud/PartiallySeparableNLPModels.jl pull request #19
Opened 2022-07-12 15:47 UTC by paraynaud

First draft of the README/index and tutorial

2022-07-12 18:56 UTC, dpo commented
Ok, let me know when I can make a pass over the tutorial.

2022-07-12 19:02 UTC, paraynaud commented
I should have done a first draft today.
I am implementing new functions for the tutorial.

2022-07-12 22:38 UTC, dpo commented
The installation instructions talk about ExpressionTreeForge and the tutorial link takes me to the ETF tutorial.

2022-07-12 22:41 UTC, paraynaud commented
Sorry, [PartiallySeparableNLPModels.jl tutorial](https://paraynaud.github.io/PartiallySeparableNLPModels.jl/dev/tutorial/)

2022-07-13 14:47 UTC, dpo requested changes

2022-07-13 14:47 UTC, dpo commented on docs/src/tutorial.md
> +As a user, you only define your `ADNLPModel`:
```suggestion
As a user, you need only define your `ADNLPModel`:
```

2022-07-13 14:47 UTC, dpo commented on docs/src/tutorial.md
> +as the sum of element function $f_i$.
```suggestion
as the sum of element functions $f_i$.
```

2022-07-13 14:47 UTC, dpo commented on docs/src/tutorial.md
> +Then, you can apply the usual methods `obj` and `grad`, exploiting the partial separability, from [NLPModels.jl](https://github.com/JuliaSmoothOptimizers/NLPModels.jl):
```suggestion
Then, you can apply the usual methods `obj` and `grad` from [NLPModels.jl](https://github.com/JuliaSmoothOptimizers/NLPModels.jl):
```

2022-07-13 14:47 UTC, dpo commented on docs/src/tutorial.md
> +Both `fx` and `gx` compute and accumulate respectively the element functions $\hat{f}_i$ and the element gradients $\nabla \hat{f}_i$.
```suggestion
`fx` and `gx` compute and accumulate the element functions $\hat{f}_i$ and the element gradients $\nabla \hat{f}_i$, respectively.
```

2022-07-13 14:47 UTC, dpo commented on docs/src/tutorial.md
> +In addition, a `PartiallySeparableNLPModel` store the value of each element gradient to perform partitioned quasi-Newton afterward.
```suggestion
In addition, a `PartiallySeparableNLPModel` stores the value of each element gradient to perform partitioned quasi-Newton updates afterward. 
```

2022-07-13 14:47 UTC, dpo commented on docs/src/tutorial.md
> +gx == NLPModels.grad(model, x)
move this before the previous paragraph.

2022-07-13 14:47 UTC, dpo commented on docs/src/tutorial.md
> +By defining a `PartiallySeparableNLPModel` you allocate a partitioned quasi-Newton update, which is implemented in `PartitionedStructures.jl`.
```suggestion
When defining a `PartiallySeparableNLPModel`, you allocate storage for partitioned quasi-Newton updates, which are implemented in `PartitionedStructures.jl`.
```

2022-07-13 14:47 UTC, dpo commented on docs/src/tutorial.md
> +The Hessian approximation of each element function $\hat{f}_i (y) = (y_1 + y_2)^2$ is initially set to an identity matrix.
$\hat{f}_i$ not defined

2022-07-13 14:47 UTC, dpo commented on docs/src/tutorial.md
> +Matrix(hess_approx(pqn_jumpnlp))
What kind of object does `hess_approx` return?

2022-07-13 14:47 UTC, dpo commented on docs/src/tutorial.md
> +and you can perform the partitioned matrix-vector product with:
```suggestion
and you can perform a partitioned-matrix-vector product with:
```

2022-07-13 14:47 UTC, dpo commented on docs/src/tutorial.md
> +B*v
This should not be necessary. Normally, `hess_op` should "just work" if your `hprod!()` follows the NLPModels API.

2022-07-13 15:10 UTC, dpo commented on docs/src/tutorial.md
> +The Hessian approximation of each element function $\hat{f}_i (y) = (y_1 + y_2)^2$ is initially set to an identity matrix.
Not really. There is $f_i$, but not $\hat{f}_i$.

2022-07-13 17:08 UTC, dpo requested changes

2022-07-13 17:08 UTC, dpo commented on docs/src/tutorial.md
>  T = eltype(x)
```suggestion
```

2022-07-13 17:15 UTC, dpo requested changes

2022-07-13 17:15 UTC, dpo commented on docs/src/tutorial.md
> +In addition, a `PartiallySeparableNLPModel` stores the value of each element gradient to perform partitioned quasi-Newton updates afterward.
```suggestion
In addition, a `PartiallySeparableNLPModel` stores the value of each element gradient to perform partitioned quasi-Newton updates afterward (see below).
```

2022-07-13 17:15 UTC, dpo commented on docs/src/tutorial.md
> +\right ]
```suggestion
\right ].
```

2022-07-13 21:59 UTC, dpo requested changes

2022-07-13 21:59 UTC, dpo commented on docs/src/tutorial.md
> +As a user, you need only define your `ADNLPModel`:
```suggestion
As a user, you need only define an `NLPModel` with an objective function implemented in pure Julia.
For instance, one may use an `ADNLPModel`:
```

2022-07-14 00:12 UTC, dpo approved these changes
let's go!

2022-07-14 00:15 UTC, merged